version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: insidegrid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: insidegrid_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "8000:80"
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80"]

volumes:
  postgres_data:
